#Set ZSH directory
ZSH=$HOME/.dotfiles/linux/zsh
DOT=$HOME/.dotfiles/linux

#set history
setopt histignorealldups sharehistory
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

setopt autocd extendedglob nomatch MENU_COMPLETE
unsetopt beep

zstyle :compinstall filename '$HOME/.zshrc'

# Use modern completion system
autoload -Uz compinit
compinit

#set default editor
export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu yes select
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#source other config files
if [ -f $DOT/aliases.sh ]; then
	source "$DOT/aliases.sh"
fi
if [ -f $DOT/local_configs.sh ]; then
	source "$DOT/local_configs.sh"
fi
if [ -f $ZSH/zsh_prompt.sh ]; then
	source "$ZSH/zsh_prompt.sh"
else 
	PROMPT="%n in %1d > "
fi
if [ -f $ZSH/zsh_functions.sh ]; then
	source "$ZSH/zsh_functions.sh"
fi

#source plugins
source "$ZSH/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$ZSH/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"

# Keybindings
bindkey -v
bindkey "^R" history-incremental-search-backward
bindkey '^k' autosuggest-accept
